# Generated by Django 5.0.4 on 2025-02-06 11:08

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=20)),
                ('capacity', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('span', models.IntegerField(blank=True, null=True)),
                ('strand', models.CharField(blank=True, null=True)),
                ('bg_gradient', models.CharField(blank=True, default='https://ccwebappbucket.s3.ap-southeast-1.amazonaws.com/uploads/bg1.png', max_length=500, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_related_class', to='accounts.facultyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GradeSheet',
            fields=[
                ('id', models.CharField(default=main.models.random_code_generator, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('quarter1', models.FloatField(blank=True, null=True)),
                ('quarter2', models.FloatField(blank=True, null=True)),
                ('quarter3', models.FloatField(blank=True, null=True)),
                ('quarter4', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('in_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_related_score', to='main.class')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_grade_entities', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('day', models.CharField(max_length=200, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('assistantprincipal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asstprincipal_related_schoolyear', to='accounts.facultyprofile')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_related_schoolyear', to='accounts.facultyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('gradelevel', models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], default='Grade 7', max_length=20)),
                ('track', models.CharField(blank=True, null=True)),
                ('bg_gradient', models.CharField(blank=True, default='https://ccwebappbucket.s3.ap-southeast-1.amazonaws.com/uploads/bg3.png', max_length=500, null=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_related_section', to='accounts.facultyprofile')),
                ('schoolyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.schoolyear')),
                ('students', models.ManyToManyField(blank=True, related_name='student_related_section', to='accounts.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.section'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('corequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_corequisite', to='main.subject')),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postrequisite', to='main.subject')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject'),
        ),
    ]
