# Generated by Django 4.2.7 on 2023-11-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=20)),
                ('capacity', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('units', models.IntegerField(default=0)),
                ('first_sem', models.BooleanField(default=True)),
                ('second_sem', models.BooleanField(default=True)),
                ('lecture', models.FloatField(default=0)),
                ('lab', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('corequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corequisites', to='main.subject')),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisites', to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('day', models.CharField(max_length=200, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_course', to='main.department')),
                ('subjects_11', models.ManyToManyField(related_name='y1s1', to='main.subject')),
                ('subjects_12', models.ManyToManyField(related_name='y1s2', to='main.subject')),
                ('subjects_21', models.ManyToManyField(related_name='y2s1', to='main.subject')),
                ('subjects_22', models.ManyToManyField(related_name='y2s2', to='main.subject')),
                ('subjects_31', models.ManyToManyField(related_name='y3s1', to='main.subject')),
                ('subjects_32', models.ManyToManyField(related_name='y3s2', to='main.subject')),
                ('subjects_41', models.ManyToManyField(related_name='y4s1', to='main.subject')),
                ('subjects_42', models.ManyToManyField(related_name='y4s2', to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('yearlevel', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(choices=[('Face to Face', 'Face to Face'), ('Virtual', 'Virtual'), ('Hybrid', 'Hybrid')], default='Face to Face', max_length=20)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course')),
                ('schedule', models.ManyToManyField(blank=True, related_name='related_class', to='main.scheduleinstance')),
                ('students', models.ManyToManyField(blank=True, related_name='student_related_class', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_related_class', to='accounts.facultyprofile')),
            ],
        ),
    ]
