# Generated by Django 5.0.1 on 2024-02-06 19:48

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentprofile_yearlevel_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_11',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_12',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_21',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_22',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_31',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_32',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_41',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_42',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='first_sem',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='second_sem',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='units',
        ),
        migrations.AlterField(
            model_name='subject',
            name='corequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_corequisite', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postrequisite', to='main.subject'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room')),
                ('schedule', models.ManyToManyField(blank=True, related_name='schedule_related_class', to='main.scheduleinstance')),
                ('students', models.ManyToManyField(blank=True, related_name='student_related_class', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_related_class', to='accounts.facultyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GradeScoreEntity',
            fields=[
                ('id', models.CharField(default=main.models.random_code_generator, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('quarter1', models.FloatField(blank=True, null=True)),
                ('quarter2', models.FloatField(blank=True, null=True)),
                ('quarter3', models.FloatField(blank=True, null=True)),
                ('quarter4', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('in_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_related_score', to='main.class')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('assistantprincipal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asstprincipal_related_schoolyear', to='accounts.facultyprofile')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_related_schoolyear', to='accounts.facultyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('gradelevel', models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], default='Grade 7', max_length=20)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.facultyprofile')),
                ('schoolyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.schoolyear')),
                ('students', models.ManyToManyField(blank=True, related_name='student_related_section', to='accounts.studentprofile')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.track')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.section'),
        ),
        migrations.AddField(
            model_name='class',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.strand'),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
