# Generated by Django 5.0.3 on 2024-03-17 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deviceprofile_rainrate'),
        ('main', '0002_gradesheet_delete_gradescoreentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_related_section', to='accounts.facultyprofile'),
        ),
    ]
