# Generated by Django 4.2.7 on 2023-11-24 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_subjects_51_course_subjects_52_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='corequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_corequisite', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postrequisite', to='main.subject'),
        ),
    ]
