# Generated by Django 5.0.3 on 2024-03-05 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_studentprofile_strand_and_more'),
        ('main', '0003_alter_section_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradescoreentity',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_grade_entities', to='accounts.studentprofile'),
        ),
    ]
