# Generated by Django 5.0.3 on 2024-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_section_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='bg_gradient',
            field=models.CharField(blank=True, default='https://ccwebappbucket.s3.ap-southeast-1.amazonaws.com/uploads/bg3.png', max_length=500, null=True),
        ),
    ]
