# Generated by Django 4.2.7 on 2023-12-17 05:15

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subject_corequisite_alter_subject_prerequisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.CharField(default=main.models.random_code_generator, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('start', models.DateField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('activity_type', models.CharField(choices=[('CAD Evaluation', 'CAD Evaluation'), ('Quiz/Exam', 'Quiz/Exam'), ('Others', 'Others')], default='CAD Evaluation', max_length=20)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('instruction', models.CharField(max_length=5000, null=True)),
                ('referencefile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
