# Generated by Django 5.0.3 on 2024-03-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_gradescoreentity_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='room',
        ),
        migrations.RemoveField(
            model_name='class',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.AddField(
            model_name='class',
            name='span',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='strand',
            field=models.CharField(blank=True, null=True),
        ),
    ]
