# Generated by Django 4.2.5 on 2023-09-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_classes_students_classes_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='teacher',
        ),
    ]
