# Generated by Django 4.2.7 on 2023-12-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_activities_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointers',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('prompt', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='pointers',
            field=models.ManyToManyField(blank=True, null=True, to='main.pointers'),
        ),
    ]
