# Generated by Django 4.2.7 on 2023-12-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pointers_activities_pointers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='pointers',
            field=models.ManyToManyField(blank=True, to='main.pointers'),
        ),
    ]
