# Generated by Django 4.2.7 on 2023-12-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_activities_pointers'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='customprompt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='activitylist',
            field=models.ManyToManyField(blank=True, related_name='in_class', to='main.activities'),
        ),
        migrations.AlterField(
            model_name='pointers',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pointers',
            name='prompt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
