# Generated by Django 4.2.7 on 2023-12-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_activities_customprompt_classes_activitylist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='activitylist',
        ),
        migrations.AddField(
            model_name='activities',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classes'),
        ),
    ]
