# Generated by Django 4.2.5 on 2023-09-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_classes_students_alter_classes_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='companystaff',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companystaff',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='licenses',
            name='service',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='normal_user',
        ),
        migrations.AddField(
            model_name='classes',
            name='room',
            field=models.CharField(default='none-allocated', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='corequisite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corequisites', to='main.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='first_sem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisites', to='main.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='second_sem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='units',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyStaff',
        ),
        migrations.DeleteModel(
            name='Licenses',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.department'),
        ),
    ]
