# Generated by Django 4.2.7 on 2023-12-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_classes_bg_gradient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='bg_gradient',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
