# Generated by Django 4.2.5 on 2023-09-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='lab',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='lecture',
            field=models.FloatField(default=0),
        ),
    ]
