# Generated by Django 4.2.5 on 2023-09-22 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_subject_lab_subject_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='type',
            field=models.CharField(choices=[('Face to Face', 'Face to Face'), ('Virtual', 'Virtual'), ('Hybrid', 'Hybrid')], default='Face to Face', max_length=20),
        ),
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(related_name='student_related_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_related_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classes',
            name='schedule',
            field=models.ManyToManyField(related_name='related_class', to='main.scheduleinstance'),
        ),
    ]
