# Generated by Django 4.2.5 on 2023-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_scheduleinstance_classes_type_alter_classes_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
