# Generated by Django 4.2.7 on 2024-01-11 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_facultyprofile_userprofile'),
        ('main', '0015_alter_activityentry_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityentry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile'),
        ),
    ]
