# Generated by Django 4.2.7 on 2024-01-12 01:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_activityentry_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityentry',
            name='id',
            field=models.CharField(default=main.models.random_code_generator, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
