# Generated by Django 4.2.5 on 2023-09-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_room_remove_classes_room_scheduleinstance_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='yearlevel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
