# Generated by Django 4.2.5 on 2023-09-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_staffprofile_role'),
        ('main', '0017_classes_yearlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(related_name='student_related_class', to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_related_class', to='accounts.facultyprofile'),
        ),
    ]
