# Generated by Django 5.0.1 on 2024-01-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_activityentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='referencefile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='pointers',
            name='prompt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
