# Generated by Django 4.2.5 on 2023-09-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_staffprofile_role'),
        ('main', '0018_alter_classes_students_alter_classes_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_related_class', to='accounts.studentprofile'),
        ),
    ]
