# Generated by Django 5.0.1 on 2024-01-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_activities_referencefile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
