# Generated by Django 5.0.1 on 2024-01-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_activityentry_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='customprompt',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='pointers',
        ),
    ]
