# Generated by Django 4.2.5 on 2023-09-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_classes_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
