# Generated by Django 5.0.1 on 2024-01-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_activities_customprompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='type',
            field=models.CharField(choices=[('Face to Face', 'Face to Face'), ('Virtual', 'Virtual'), ('Hybrid', 'Hybrid')], default='Face to Face', max_length=200),
        ),
    ]
