# Generated by Django 5.0.1 on 2024-01-31 16:24

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_facultyprofile_courses_and_more'),
        ('main', '0021_alter_classes_code_alter_classes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room')),
                ('schedule', models.ManyToManyField(blank=True, related_name='schedule_related_class', to='main.scheduleinstance')),
                ('students', models.ManyToManyField(blank=True, related_name='student_related_class', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GradeScoreEntity',
            fields=[
                ('id', models.CharField(default=main.models.random_code_generator, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('quarter1', models.FloatField(blank=True, null=True)),
                ('quarter2', models.FloatField(blank=True, null=True)),
                ('quarter3', models.FloatField(blank=True, null=True)),
                ('quarter4', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('assistantprincipal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asstprincipal_related_schoolyear', to='accounts.facultyprofile')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_related_schoolyear', to='accounts.facultyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('gradelevel', models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], default='Grade 7', max_length=20)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.facultyprofile')),
                ('schoolyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.schoolyear')),
                ('students', models.ManyToManyField(blank=True, related_name='student_related_section', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activities',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='activityentry',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityentry',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_11',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_12',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_21',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_22',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_31',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_32',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_41',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_42',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_51',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects_52',
        ),
        migrations.DeleteModel(
            name='Pointers',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='first_sem',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='second_sem',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='units',
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_related_class', to='accounts.facultyprofile'),
        ),
        migrations.AddField(
            model_name='gradescoreentity',
            name='in_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_related_score', to='main.class'),
        ),
        migrations.AddField(
            model_name='gradescoreentity',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.section'),
        ),
        migrations.AddField(
            model_name='class',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.strand'),
        ),
        migrations.AddField(
            model_name='section',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.track'),
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.DeleteModel(
            name='ActivityEntry',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
