# Generated by Django 4.2.5 on 2023-09-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_classes_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleinstance',
            name='day',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
