# Generated by Django 4.2.5 on 2023-10-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_scheduleinstance_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
