# Generated by Django 4.2.5 on 2023-10-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_classes_enddate_classes_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
