# Generated by Django 4.2.5 on 2023-10-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_classes_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='schedule',
        ),
        migrations.AddField(
            model_name='classes',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_class', to='main.scheduleinstance'),
        ),
    ]
