# Generated by Django 4.2.5 on 2023-10-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_classes_schedule_classes_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='schedule',
        ),
        migrations.AddField(
            model_name='classes',
            name='schedule',
            field=models.ManyToManyField(blank=True, related_name='related_class', to='main.scheduleinstance'),
        ),
    ]
