# Generated by Django 4.2.5 on 2023-10-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_classes_schedule_classes_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course'),
        ),
    ]
