# Generated by Django 5.0.4 on 2025-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
