# Generated by Django 5.0.3 on 2024-03-12 08:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.CharField(default=accounts.models.random_code_generator, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('triggercount', models.IntegerField(blank=True, null=True)),
                ('hourcount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
