# Generated by Django 5.0.4 on 2025-02-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_events_time_end_events_time_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time_start',
        ),
        migrations.AddField(
            model_name='events',
            name='timeend',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='timestart',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
