# Generated by Django 5.0.3 on 2024-03-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deviceprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='hourcount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
