# Generated by Django 5.0.1 on 2024-02-06 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentprofile_yearlevel_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_strand_track_remove_course_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.track'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='userprofile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='address_value1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_value2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_value3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='addressketch',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatar.webp', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthplace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='extension_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='position',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Assistant Principal', 'Assistant Principal'), ('Part-Time', 'Part-Time'), ('Teacher-1', 'Teacher-1'), ('Teacher-2', 'Teacher-2'), ('Teacher-3', 'Teacher-3'), ('Laboratory Attendant', 'Laboratory Attendant'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('For Evaluation', 'For Evaluation'), ('Evaluation In Progress', 'Evaluation In Progress'), ('Pending Payment', 'Pending Payment'), ('Enrolled', 'Enrolled')], default='For Evaluation', max_length=50),
        ),
    ]
