# Generated by Django 5.0.1 on 2024-01-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_facultyprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatar.webp', upload_to='uploads/'),
        ),
    ]
