# Generated by Django 4.2.7 on 2024-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_strand_studentprofile_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='petpclc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='petpclcjhs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
