# Generated by Django 5.0.4 on 2025-02-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_events_time_end_remove_events_time_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='timeend',
        ),
        migrations.RemoveField(
            model_name='events',
            name='timestart',
        ),
        migrations.AddField(
            model_name='events',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
