# Generated by Django 5.0.3 on 2024-03-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_deviceprofile_hourcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='rainrate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
