# Generated by Django 5.0.3 on 2024-03-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deviceprofile_rainrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='waterlevel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gradelevel',
            field=models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Graduated', 'Graduated')], default='Grade 7', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('For Evaluation', 'For Evaluation'), ('Evaluation In Progress', 'Evaluation In Progress'), ('Pending Payment', 'Pending Payment'), ('Enrolled', 'Enrolled')], default='Enrolled', max_length=50),
        ),
    ]
