# Generated by Django 4.2.7 on 2024-02-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_petpclc_studentprofile_petpclcjhs'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='shs2address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
