# Generated by Django 5.0.4 on 2025-02-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_events_timeend_remove_events_timestart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='created_by',
        ),
    ]
