# Generated by Django 4.2.7 on 2024-02-18 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_strand_track_remove_course_department_and_more'),
        ('accounts', '0005_studentprofile_shs2address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.track'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.strand'),
        ),
    ]
