# Generated by Django 5.0.1 on 2024-01-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentprofile_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='yearlevel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suspended',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ae',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='aecompletion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='aecompletionjhs',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='aejhs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='clc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='clcaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='clcaddressjhs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='clcjhs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='elementaryaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='elementarycompletiondate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='elementaryregion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='elementaryschool',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gradelevel',
            field=models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], default='Grade 7', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='jhs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='jhsaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='jhsaverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='jhscompletion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='jhsregion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pept',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='peptcompletion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='peptcompletionjhs',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='peptjhs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs1address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs1strand1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs1strand2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs1track1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs1track2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs2strand1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs2strand2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs2track1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs2track2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
