# Generated by Django 5.0.4 on 2025-02-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_events_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='events',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
        migrations.RemoveField(
            model_name='events',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='events',
            name='description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='link',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time_start',
        ),
    ]
