# Generated by Django 5.0.3 on 2024-03-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_deviceprofile_waterlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('For Evaluation', 'For Evaluation'), ('Evaluation In Progress', 'Evaluation In Progress'), ('Pending Payment', 'Pending Payment'), ('Enrolled', 'Enrolled')], default='Enrolled', max_length=50),
        ),
    ]
