# Generated by Django 5.0.1 on 2024-01-31 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_facultyprofile_courses_and_more'),
        ('main', '0022_class_gradescoreentity_schoolyear_section_strand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.track'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthplace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='position',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Assistant Principal', 'Assistant Principal'), ('Part-Time', 'Part-Time'), ('Teacher-1', 'Teacher-1'), ('Teacher-2', 'Teacher-2'), ('Teacher-3', 'Teacher-3'), ('Laboratory Attendant', 'Laboratory Attendant'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('For Evaluation', 'For Evaluation'), ('Evaluation In Progress', 'Evaluation In Progress'), ('Pending Payment', 'Pending Payment'), ('Enrolled', 'Enrolled')], default='Draft', max_length=50),
        ),
    ]
