# Generated by Django 4.2.7 on 2024-02-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_track_alter_studentprofile_strand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='strand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='track',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
