# Generated by Django 5.0.4 on 2025-02-06 11:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_events_approval_remove_events_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsList',
            fields=[
                ('id', models.CharField(default=accounts.models.random_code_generator, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='approval',
            field=models.CharField(blank=True, default='No', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='avatar',
            field=models.FileField(default='avatar.webp', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Allow-Conflict', 'Allow-Conflict'), ('No-Conflict', 'No-Conflict'), ('Special-Event', 'Special-Event'), ('Not-Specified', 'Not-Specified')], default='Not-Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
