# Generated by Django 5.0.1 on 2024-02-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile_strand_user_birthdate_user_birthplace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_value',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='facebook_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_relationship',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_relationship',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_relationship',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_value1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_value2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_value3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='extension_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
