# Generated by Django 5.0.4 on 2025-02-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_eventslist_events_approval_events_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='approval',
            field=models.CharField(blank=True, default='No', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='avatar',
            field=models.FileField(default='avatar.webp', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='category',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Allow-Conflict', 'Allow-Conflict'), ('No-Conflict', 'No-Conflict'), ('Special-Event', 'Special-Event'), ('Not-Specified', 'Not-Specified')], default='Not-Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
