# Generated by Django 5.0.1 on 2024-02-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_address_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_relationship',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_relationship',
        ),
    ]
