# Generated by Django 5.0.4 on 2025-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_eventslist_approval_eventslist_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
