# Generated by Django 4.2.5 on 2023-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_studentprofile_user_user_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yearlevel',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('Irregular', 'Irregular')], default='1st', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
