# Generated by Django 4.2.5 on 2023-09-14 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_yearlevel_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='yearlevel',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('Verification Failed', 'Verification Failed'), ('For Evaluation', 'For Evaluation'), ('Evaluation Complete', 'Evalutation Complete')], default='For Evaluation', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='yearlevel',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('Irregular', 'Irregular')], default='1st', max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='not specified', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
