# Generated by Django 5.0.4 on 2025-02-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_eventslist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
