# Generated by Django 5.0.1 on 2024-02-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_studentprofile_father_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='addressketch',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
