# Generated by Django 4.2.5 on 2023-09-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_yearlevel_studentprofile_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
