# Generated by Django 5.0.4 on 2025-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_eventslist_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
