# Generated by Django 5.0.1 on 2024-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_studentprofile_addressketch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='addressketch',
        ),
        migrations.AddField(
            model_name='user',
            name='addressketch',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
