# Generated by Django 4.2.5 on 2023-09-14 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('Verification Failed', 'Verification Failed'), ('For Evaluation', 'For Evaluation'), ('Evaluation Complete', 'Evaluation Complete')], default='For Evaluation', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile'),
        ),
    ]
