# Generated by Django 5.0.4 on 2025-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_eventslist_date'),
        ('main', '0002_alter_section_gradelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='staff_related_event', to='accounts.schedulestaffprofile'),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='section_related_event', to='main.section'),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
