# Generated by Django 5.0.4 on 2025-02-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_eventslist_participants_eventslist_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
