# Generated by Django 4.2.5 on 2023-09-15 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_studentprofile_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='studentprofile',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='userprofile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
