# Generated by Django 4.2.5 on 2023-09-15 00:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_studentprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.CharField(default=accounts.models.student_code_generator, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
