# Generated by Django 5.0.4 on 2025-02-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_eventslist_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='conflict',
            field=models.CharField(choices=[('Allow-Conflict', 'Allow-Conflict'), ('No-Conflict', 'No-Conflict')], default='Allow-Conflict', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='category',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Special-Event', 'Special-Event'), ('Academic-Event', 'Academinc-Event'), ('Not-Specified', 'Not-Specified')], default='Not-Specified', max_length=50),
        ),
    ]
