# Generated by Django 5.0.4 on 2025-02-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_eventslist_conflict_alter_eventslist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='created_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
