# Generated by Django 5.0.4 on 2025-02-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_eventslist_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
