# Generated by Django 5.0.4 on 2025-02-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_eventslist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='participants_additional',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
