# Generated by Django 4.2.5 on 2023-09-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_facultyprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyprofile',
            old_name='course',
            new_name='courses',
        ),
    ]
