# Generated by Django 4.2.5 on 2023-09-21 10:40

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_course_facultyprofile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='position',
            field=models.CharField(choices=[('Dean', 'Dean'), ('Assistant Dean', 'Assistant Dean'), ('Professor', 'Professor'), ('Part-Time', 'Part-Time'), ('Teacher', 'Teacher'), ('Laboratory Attendant', 'Laboratory Attendant')], default='Teacher', max_length=50),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.CharField(default=accounts.models.student_code_generator, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Sub-Admin', 'Sub-Admin'), ('Not Specified', 'Not Specified'), ('Registrar', 'Registrar'), ('Guidance', 'Guidance')], default='Not Specified', max_length=50)),
                ('userprofile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
