# Generated by Django 5.0.4 on 2025-02-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_eventslist_participants_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='faculty_related_event', to='accounts.facultyprofile'),
        ),
    ]
