# Generated by Django 5.0.4 on 2025-02-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_eventslist_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
