# Generated by Django 4.2.5 on 2023-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_facultyprofile_position_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Not Specified', 'Not Specified'), ('Registrar', 'Registrar'), ('Guidance', 'Guidance')], default='Not Specified', max_length=50),
        ),
    ]
