# Generated by Django 5.0.4 on 2025-02-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_eventslist_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventslist',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='eventslist',
            name='students',
        ),
    ]
