# Generated by Django 5.0.4 on 2025-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_eventslist_avatar_remove_eventslist_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='meetlink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='type',
            field=models.CharField(choices=[('Face-To-Face', 'Face-To-Face'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], default='Face-To-Face', max_length=50),
        ),
    ]
