# Generated by Django 5.0.4 on 2025-03-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_eventslist_meetlink_eventslist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='type',
            field=models.CharField(choices=[('Face-To-Face', 'Face-To-Face'), ('Online', 'Online'), ('Hybrid', 'Hybrid'), ('Holiday', 'Holiday')], default='Face-To-Face', max_length=50),
        ),
    ]
