# Generated by Django 5.0.4 on 2025-03-07 04:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_eventimages_eventslist_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimages',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
