# Generated by Django 5.0.4 on 2025-03-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_eventslist_photos_eventimages_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='in_charge',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
