# Generated by Django 4.2.7 on 2025-03-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_eventslist_in_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='category',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Special-Event', 'Special-Event'), ('Academic-Event', 'Academic-Event'), ('Private-Event', 'Private-Event'), ('Not-Specified', 'Not-Specified')], default='Not-Specified', max_length=50),
        ),
    ]
