# Generated by Django 5.0.4 on 2025-03-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_facultyprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='waterlevel2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
