# Generated by Django 5.0.4 on 2025-03-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_deviceprofile_waterlevel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='waterlevelwarning2',
            field=models.CharField(blank=True, null=True),
        ),
    ]
