export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const BAD_REQUEST = 'BAD_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_USERS = 'GET_USERS';
export const DELETE_USER = 'DELETE_USER';
export const ACCESS_VERIFY_SUCCESS = 'ACCESS_VERIFY_SUCCESS';

export const ERROR_MAIN = "ERROR_MAIN";
export const NULL_ERROR = "NULL_ERROR";
export const NULL_ERROR_MAIN = "NULL_ERROR_MAIN";
export const SET_LOADING_USER = "SET_LOADING_USER";
export const SET_LOADING = 'SET_LOADING';

export const SET_SIDEBAR = 'SET_SIDEBAR';
export const SET_SUBSIDEBAR = 'SET_SUBSIDEBAR';
export const SET_CLASS = 'SET_CLASS';
export const SET_SUBJECT = 'SET_SUBJECT';
export const SET_ROOM = 'SET_ROOM';
export const SET_COURSE = 'SET_COURSE';
export const SET_SECTION = 'SET_SECTION';

export const SET_PAGEHEADER = 'SET_PAGEHEADER';
export const SET_SUBJECT_FORMDATA = 'SET_SUBJECT_FORMDATA';

export const GET_STUDENTS = 'GET_STUDENTS'
export const GET_FACULTY = 'GET_FACULTY'
export const GET_STAFF = 'GET_STAFF'
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'
export const GET_COURSES = 'GET_COURSES'
export const GET_SUBJECT = 'GET_SUBJECT'
export const GET_ROOMS = 'GET_ROOMS'
export const GET_CLASSES = 'GET_CLASSES'
export const GET_CLASSES_LIST = 'GET_CLASSES_LIST'
export const GET_SUBJECTS_LIST = 'GET_SUBJECTS_LIST'
export const GET_ROOMS_LIST = 'GET_ROOMS_LIST'
export const GET_COURSES_LIST = 'GET_COURSES_LIST'
export const GET_SECTION = 'GET_SECTION'

export const ADD_CLASS = 'ADD_CLASS'
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const ADD_ROOM = 'ADD_ROOM'
export const ADD_COURSE = 'ADD_COURSE'

export const RESO_UPDATE = 'RESO_UPDATE'
export const AUTO_COLLAPSE = 'AUTO_COLLAPSE'
export const CLEAR_STATE = 'CLEAR_STATE'

export const REGISTER_STUDENT = 'REGISTER_STUDENT'
export const REGISTER_TEACHER = 'REGISTER_TEACHER'

export const FILL_ERROR = 'FILL_ERROR'
export const EMPTY_ERROR = 'EMPTY_ERROR'
export const EMPTY_SUCCESS = 'EMPTY_SUCCESS'

//portal

export const GET_TEACHER_DATA = 'GET_TEACHER_DATA'
export const SET_SELECTED_CLASS = 'SET_SELECTED_CLASS'
export const GET_POINTERS = 'GET_POINTERS'
export const ADD_ACTIVITY = 'ADD_ACTIVITY'
export const GET_ACTIVITIES = 'GET_ACTIVITIES'
export const GET_ACTIVITY = 'GET_ACTIVITY'
export const SET_BG = 'SET_BG'
export const SET_SELECTED_BG = 'SET_SELECTED_BG'
export const GET_CLASS_DATA = 'GET_CLASS_DATA'
export const GET_ENTRY = 'GET_ENTRY'
export const SET_SUBMITTING_STUDENT = 'SET_SUBMITTING_STUDENT'
export const SET_USER_AVATAR = 'SET_USER_AVATAR'
export const SET_USER_DATA = 'SET_USER_DATA'
export const GET_STUDENT_DATA = 'GET_STUDENT_DATA'
export const ADD_ACTIVITY_ENTRY = 'ADD_ACTIVITY_ENTRY'
export const SET_USER_PW = 'SET_USER_PW'

export const ANALYZE_IMAGES_SUCCESS = 'ANALYZE_IMAGES_SUCCESS'

export const CLEAR_RESPONSE = 'CLEAR_RESPONSE'

//enrollment

export const GET_SCHOOLYEAR = 'GET_SCHOOLYEAR'