export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_USERS = 'GET_USERS';
export const DELETE_USER = 'DELETE_USER';
export const ACCESS_VERIFY_SUCCESS = 'ACCESS_VERIFY_SUCCESS';
export const SET_LOADING = 'SET_LOADING';

export const SET_SIDEBAR = 'SET_SIDEBAR';
export const SET_SUBSIDEBAR = 'SET_SUBSIDEBAR';

export const SET_PAGEHEADER = 'SET_PAGEHEADER';

export const GET_STUDENTS = 'GET_STUDENTS'
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'